# Generated by Django 4.1.3 on 2022-12-04 18:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer', models.CharField(max_length=200, verbose_name='Вариант ответа')),
                ('is_true', models.BooleanField(default=False, verbose_name='Правильный ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Обновлён')),
            ],
        ),
        migrations.CreateModel(
            name='Quest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quest', models.CharField(max_length=200, verbose_name='Вопрос')),
                ('max_score', models.DecimalField(decimal_places=2, default=1, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Обновлён')),
            ],
        ),
        migrations.CreateModel(
            name='QuizCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('update_at', models.DateField(auto_now=True, verbose_name='Обновлён')),
            ],
        ),
        migrations.CreateModel(
            name='QUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_score', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Количество очков')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Result',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_true', models.BooleanField(default=False)),
                ('score', models.DecimalField(decimal_places=2, default=0, max_digits=6, verbose_name='Оценка')),
                ('answer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.answer')),
                ('quest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.quest')),
                ('quiz_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='main.quser')),
            ],
        ),
        migrations.AddField(
            model_name='quest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='main.quizcategory', verbose_name='Категория'),
        ),
        migrations.AddField(
            model_name='answer',
            name='quest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='main.quest'),
        ),
    ]
